openapi: 3.0.0
info:
  description: |
    API for the transpaer backend
  title: Transpaer
  version: 0.1.0
servers:
- url: /
paths:
  /:
    get:
      description: Service health check.
      operationId: checkHealth
      responses:
        "200":
          description: Ok
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
      summary: Health check
  /search/text:
    get:
      description: Returns results of a search using a text query.
      operationId: searchByText
      parameters:
      - description: Text query for search.
        explode: true
        in: query
        name: query
        required: true
        schema:
          $ref: '#/components/schemas/shortString'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/textSearchResults'
          description: Ok
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
      summary: Text search.
  /library:
    get:
      description: Returns a list of summaries of all library items.
      operationId: getLibrary
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/libraryContents'
          description: Ok
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
      summary: Get library contents.
  /library/{topic}:
    get:
      description: Returns a full library item.
      operationId: getLibraryItem
      parameters:
      - description: Library topic.
        explode: false
        in: path
        name: topic
        required: true
        schema:
          $ref: '#/components/schemas/libraryTopic'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/libraryItemFull'
          description: Ok
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
        "404":
          description: Not found
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
      summary: Get library item.
  /organisation/{organisationIdVariant}:{id}:
    get:
      description: Returns full info about a specified organisation.
      operationId: getOrganisation
      parameters:
      - description: Variant of an organisation ID.
        explode: false
        in: path
        name: organisationIdVariant
        required: true
        schema:
          $ref: '#/components/schemas/organisationIdVariant'
        style: simple
      - description: ID of a resource.
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/id'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organisationFull'
          description: Ok
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
        "404":
          description: Not found
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
      summary: Get organisation.
  /product/{productIdVariant}:{id}:
    get:
      description: Returns full info about a specified product.
      operationId: getProduct
      parameters:
      - description: Variant of a product ID.
        explode: false
        in: path
        name: productIdVariant
        required: true
        schema:
          $ref: '#/components/schemas/productIdVariant'
        style: simple
      - description: ID of a resource.
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/id'
        style: simple
      - description: Region code.
        explode: true
        in: query
        name: region
        required: false
        schema:
          $ref: '#/components/schemas/regionCode'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productFull'
          description: Ok
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
        "404":
          description: Not found
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
      summary: Get product.
  /product/{productIdVariant}:{id}/alternatives:
    get:
      description: Returns a list of alternative products for each of products category.
      operationId: getAlternatives
      parameters:
      - description: Variant of a product ID.
        explode: false
        in: path
        name: productIdVariant
        required: true
        schema:
          $ref: '#/components/schemas/productIdVariant'
        style: simple
      - description: ID of a resource.
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/id'
        style: simple
      - description: Region code.
        explode: true
        in: query
        name: region
        required: false
        schema:
          $ref: '#/components/schemas/regionCode'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/categoryAlternatives'
                type: array
          description: Ok
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
        "404":
          description: Not found
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
      summary: Get product alternatives.
  /category/{category}:
    get:
      description: Returns full info about a specified category.
      operationId: getCategory
      parameters:
      - description: Category path.
        explode: false
        in: path
        name: category
        required: true
        schema:
          $ref: '#/components/schemas/category'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/categoryFull'
          description: Ok
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
        "404":
          description: Not found
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/corsOrigin'
            Access-Control-Allow-Methods:
              $ref: '#/components/headers/corsMethods'
            Access-Control-Allow-Headers:
              $ref: '#/components/headers/corsHeaders'
      summary: Get category.
components:
  headers:
    corsOrigin:
      explode: false
      required: true
      schema:
        type: string
      style: simple
    corsMethods:
      explode: false
      required: true
      schema:
        type: string
      style: simple
    corsHeaders:
      explode: false
      required: true
      schema:
        type: string
      style: simple
  parameters:
    organisationIdVariant:
      description: Variant of an organisation ID.
      explode: false
      in: path
      name: organisationIdVariant
      required: true
      schema:
        $ref: '#/components/schemas/organisationIdVariant'
      style: simple
    productIdVariant:
      description: Variant of a product ID.
      explode: false
      in: path
      name: productIdVariant
      required: true
      schema:
        $ref: '#/components/schemas/productIdVariant'
      style: simple
    id:
      description: ID of a resource.
      explode: false
      in: path
      name: id
      required: true
      schema:
        $ref: '#/components/schemas/id'
      style: simple
    category:
      description: Category path.
      explode: false
      in: path
      name: category
      required: true
      schema:
        $ref: '#/components/schemas/category'
      style: simple
    regionCode:
      description: Region code.
      explode: true
      in: query
      name: region
      required: false
      schema:
        $ref: '#/components/schemas/regionCode'
      style: form
    libraryTopic:
      description: Library topic.
      explode: false
      in: path
      name: topic
      required: true
      schema:
        $ref: '#/components/schemas/libraryTopic'
      style: simple
    query:
      description: Text query for search.
      explode: true
      in: query
      name: query
      required: true
      schema:
        $ref: '#/components/schemas/shortString'
      style: form
  schemas:
    shortString:
      description: "Short string for labels, titles, summaries..."
      maxLength: 1024
      type: string
    textSearchResults:
      description: List of results of a text search.
      example:
        results:
        - link:
            product_id_variant: ean
            id: id
            organisation_id_variant: wiki
          label: label
        - link:
            product_id_variant: ean
            id: id
            organisation_id_variant: wiki
          label: label
      properties:
        results:
          items:
            $ref: '#/components/schemas/textSearchResult'
          type: array
      required:
      - results
      type: object
    textSearchResult:
      description: An entry in text search results.
      example:
        link:
          product_id_variant: ean
          id: id
          organisation_id_variant: wiki
        label: label
      properties:
        link:
          $ref: '#/components/schemas/textSearchLinkHack'
        label:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
      required:
      - label
      - link
      type: object
    textSearchLinkHack:
      description: Link to a text search result.
      example:
        product_id_variant: ean
        id: id
        organisation_id_variant: wiki
      properties:
        organisation_id_variant:
          $ref: '#/components/schemas/organisationIdVariant'
        product_id_variant:
          $ref: '#/components/schemas/productIdVariant'
        id:
          description: ID of a resource.
          maxLength: 32
          type: string
      required:
      - id
      type: object
    organisationIdVariant:
      description: Enumerates organisation ID variants.
      enum:
      - wiki
      - vat
      - www
      type: string
    productIdVariant:
      description: Enumerates product ID variants.
      enum:
      - ean
      - gtin
      - wiki
      type: string
    id:
      description: ID of a resource.
      maxLength: 32
      type: string
    libraryContents:
      description: List of all items in the library.
      example:
        items:
        - summary: summary
          id: wiki
          title: title
        - summary: summary
          id: wiki
          title: title
      properties:
        items:
          items:
            $ref: '#/components/schemas/libraryItemShort'
          type: array
      required:
      - items
      type: object
    libraryItemShort:
      description: Short summary of a library item.
      example:
        summary: summary
        id: wiki
        title: title
      properties:
        id:
          $ref: '#/components/schemas/libraryTopic'
        title:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
        summary:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
      required:
      - id
      - summary
      - title
      type: object
    libraryTopic:
      description: Name of a topic in the library.
      enum:
      - wiki
      - open_food_facts
      - bcorp
      - eu_ecolabel
      - tco
      - fti
      type: string
    libraryItemFull:
      description: Full contents of a library item.
      example:
        summary: summary
        presentation:
          data:
          - score: 0
            name: name
            wiki_id: wiki_id
          - score: 0
            name: name
            wiki_id: wiki_id
        links:
        - link: link
          title: title
        - link: link
          title: title
        id: wiki
        title: title
        article: article
      properties:
        id:
          $ref: '#/components/schemas/libraryTopic'
        title:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
        summary:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
        article:
          description: "Long string for descriptions, articles..."
          maxLength: 1048576
          type: string
        links:
          items:
            $ref: '#/components/schemas/referenceLink'
          type: array
        presentation:
          $ref: '#/components/schemas/presentation'
      required:
      - article
      - id
      - links
      - summary
      - title
      type: object
    longString:
      description: "Long string for descriptions, articles..."
      maxLength: 1048576
      type: string
    referenceLink:
      description: A reference link
      example:
        link: link
        title: title
      properties:
        title:
          type: string
        link:
          type: string
      required:
      - link
      - title
      type: object
    presentation:
      description: Additional data to present together with a library item.
      example:
        data:
        - score: 0
          name: name
          wiki_id: wiki_id
        - score: 0
          name: name
          wiki_id: wiki_id
      properties:
        data:
          items:
            $ref: '#/components/schemas/presentationEntry'
          type: array
      required:
      - data
      type: object
    presentationEntry:
      description: An entry in a presentation.
      example:
        score: 0
        name: name
        wiki_id: wiki_id
      properties:
        wiki_id:
          description: ID of a resource.
          maxLength: 32
          type: string
        name:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
        score:
          type: integer
      required:
      - name
      - score
      - wiki_id
      type: object
    organisationFull:
      description: Full organisation data.
      example:
        images:
        - image: image
          source: null
        - image: image
          source: null
        names:
        - text: text
          source: transpaer
        - text: text
          source: transpaer
        medallions:
        - euEcolabel:
            matchAccuracy: 0.6027456183070403
          tco:
            brandName: brandName
          transpaer:
            score:
              total: 5.962133916683182
              tree:
              - score: 2.3021358869347655
                weight: 5
                category: dataAvailability
                branches:
                - null
                - null
              - score: 2.3021358869347655
                weight: 5
                category: dataAvailability
                branches:
                - null
                - null
          variant: bCorp
          fti:
            score: 1
          bcorp:
            report_url: report_url
            id: id
        - euEcolabel:
            matchAccuracy: 0.6027456183070403
          tco:
            brandName: brandName
          transpaer:
            score:
              total: 5.962133916683182
              tree:
              - score: 2.3021358869347655
                weight: 5
                category: dataAvailability
                branches:
                - null
                - null
              - score: 2.3021358869347655
                weight: 5
                category: dataAvailability
                branches:
                - null
                - null
          variant: bCorp
          fti:
            score: 1
          bcorp:
            report_url: report_url
            id: id
        origins:
        - null
        - null
        websites:
        - null
        - null
        media:
        - mentions:
          - link: link
            title: title
          - link: link
            title: title
          icon: icon
        - mentions:
          - link: link
            title: title
          - link: link
            title: title
          icon: icon
        descriptions:
        - text: text
          source: null
        - text: text
          source: null
        organisationIds:
          wiki:
          - null
          - null
          vat:
          - null
          - null
          domains:
          - null
          - null
        products:
        - badges:
          - bcorp
          - bcorp
          productIds:
            gtins:
            - null
            - null
            wiki:
            - null
            - null
            eans:
            - null
            - null
          scores:
          - score: 0
            scorerName: fti
          - score: 0
            scorerName: fti
          name: name
          description:
            text: text
            source: null
        - badges:
          - bcorp
          - bcorp
          productIds:
            gtins:
            - null
            - null
            wiki:
            - null
            - null
            eans:
            - null
            - null
          scores:
          - score: 0
            scorerName: fti
          - score: 0
            scorerName: fti
          name: name
          description:
            text: text
            source: null
      properties:
        organisationIds:
          $ref: '#/components/schemas/organisationIds'
        names:
          items:
            $ref: '#/components/schemas/shortText'
          type: array
        descriptions:
          items:
            $ref: '#/components/schemas/longText'
          type: array
        images:
          items:
            $ref: '#/components/schemas/image'
          type: array
        websites:
          items:
            $ref: '#/components/schemas/shortString'
          type: array
        origins:
          items:
            $ref: '#/components/schemas/regionCode'
          type: array
        media:
          items:
            $ref: '#/components/schemas/medium'
          type: array
        products:
          items:
            $ref: '#/components/schemas/productShort'
          type: array
        medallions:
          items:
            $ref: '#/components/schemas/medallion'
          type: array
      required:
      - descriptions
      - images
      - medallions
      - names
      - organisationIds
      - products
      - websites
      type: object
    organisationIds:
      description: IDs of an organisation.
      example:
        wiki:
        - null
        - null
        vat:
        - null
        - null
        domains:
        - null
        - null
      properties:
        wiki:
          items:
            $ref: '#/components/schemas/id'
          type: array
        vat:
          items:
            $ref: '#/components/schemas/id'
          type: array
        domains:
          items:
            $ref: '#/components/schemas/id'
          type: array
      type: object
    shortText:
      description: Short text with its source.
      example:
        text: text
        source: transpaer
      properties:
        text:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
        source:
          $ref: '#/components/schemas/dataSource'
      required:
      - source
      - text
      type: object
    dataSource:
      description: Describes where the related data was retrieved from.
      enum:
      - transpaer
      - wiki
      - "off"
      - eu
      - b_corp
      - fti
      - tco
      - other
      type: string
    longText:
      description: Long text with its source.
      example:
        text: text
        source: null
      properties:
        text:
          description: "Long string for descriptions, articles..."
          maxLength: 1048576
          type: string
        source:
          $ref: '#/components/schemas/dataSource'
      required:
      - source
      - text
      type: object
    image:
      description: Image path/URL with its source.
      example:
        image: image
        source: null
      properties:
        image:
          type: string
        source:
          $ref: '#/components/schemas/dataSource'
      required:
      - image
      - source
      type: object
    regionCode:
      description: Code of a region.
      maxLength: 3
      minLength: 3
      type: string
    medium:
      example:
        mentions:
        - link: link
          title: title
        - link: link
          title: title
        icon: icon
      properties:
        mentions:
          items:
            $ref: '#/components/schemas/mention'
          type: array
        icon:
          type: string
      required:
      - mentions
      type: object
    mention:
      example:
        link: link
        title: title
      properties:
        title:
          type: string
        link:
          type: string
      required:
      - link
      - title
      type: object
    productShort:
      description: Extract from product data.
      example:
        badges:
        - bcorp
        - bcorp
        productIds:
          gtins:
          - null
          - null
          wiki:
          - null
          - null
          eans:
          - null
          - null
        scores:
        - score: 0
          scorerName: fti
        - score: 0
          scorerName: fti
        name: name
        description:
          text: text
          source: null
      properties:
        productIds:
          $ref: '#/components/schemas/productIds'
        name:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
        description:
          $ref: '#/components/schemas/longText'
        badges:
          items:
            $ref: '#/components/schemas/badgeName'
          type: array
        scores:
          items:
            $ref: '#/components/schemas/score'
          type: array
      required:
      - badges
      - name
      - productIds
      - scores
      type: object
    productIds:
      description: IDs of a product.
      example:
        gtins:
        - null
        - null
        wiki:
        - null
        - null
        eans:
        - null
        - null
      properties:
        eans:
          items:
            $ref: '#/components/schemas/id'
          type: array
        gtins:
          items:
            $ref: '#/components/schemas/id'
          type: array
        wiki:
          items:
            $ref: '#/components/schemas/id'
          type: array
      type: object
    badgeName:
      description: Name of a badge.
      enum:
      - bcorp
      - eu
      - tco
      type: string
    score:
      description: score.
      example:
        score: 0
        scorerName: fti
      properties:
        scorerName:
          $ref: '#/components/schemas/scorerName'
        score:
          format: int64
          type: integer
      required:
      - score
      - scorerName
      type: object
    scorerName:
      description: Name of a scorer.
      enum:
      - fti
      type: string
    medallion:
      description: Combines data from any medallion.
      example:
        euEcolabel:
          matchAccuracy: 0.6027456183070403
        tco:
          brandName: brandName
        transpaer:
          score:
            total: 5.962133916683182
            tree:
            - score: 2.3021358869347655
              weight: 5
              category: dataAvailability
              branches:
              - null
              - null
            - score: 2.3021358869347655
              weight: 5
              category: dataAvailability
              branches:
              - null
              - null
        variant: bCorp
        fti:
          score: 1
        bcorp:
          report_url: report_url
          id: id
      properties:
        variant:
          $ref: '#/components/schemas/medallionVariant'
        bcorp:
          $ref: '#/components/schemas/bCorpMedallion'
        euEcolabel:
          $ref: '#/components/schemas/euEcolabelMedallion'
        fti:
          $ref: '#/components/schemas/ftiMedallion'
        transpaer:
          $ref: '#/components/schemas/transpaerMedallion'
        tco:
          $ref: '#/components/schemas/tcoMedallion'
      required:
      - variant
      type: object
    medallionVariant:
      description: Medallion variant.
      enum:
      - bCorp
      - euEcolabel
      - fti
      - transpaer
      - tco
      type: string
    bCorpMedallion:
      description: Details of BCorp evaluation.
      example:
        report_url: report_url
        id: id
      properties:
        id:
          description: ID of a resource.
          maxLength: 32
          type: string
        report_url:
          description: "Long string for descriptions, articles..."
          maxLength: 1048576
          type: string
      required:
      - id
      - report_url
      type: object
    euEcolabelMedallion:
      description: Details of EU Ecolabel evaluation.
      example:
        matchAccuracy: 0.6027456183070403
      properties:
        matchAccuracy:
          description: Match accuracy.
          format: double
          maximum: 1.0
          minimum: 0.0
          type: number
      type: object
    accuracy:
      description: Match accuracy.
      format: double
      maximum: 1.0
      minimum: 0.0
      type: number
    ftiMedallion:
      description: Details of Fashion Transparency Index evaluation.
      example:
        score: 1
      properties:
        score:
          format: int64
          type: integer
      required:
      - score
      type: object
    transpaerMedallion:
      description: Details of Transpaer evaluation.
      example:
        score:
          total: 5.962133916683182
          tree:
          - score: 2.3021358869347655
            weight: 5
            category: dataAvailability
            branches:
            - null
            - null
          - score: 2.3021358869347655
            weight: 5
            category: dataAvailability
            branches:
            - null
            - null
      properties:
        score:
          $ref: '#/components/schemas/transpaerScore'
      required:
      - score
      type: object
    transpaerScore:
      description: Explanation of calculation of the Transpaer score.
      example:
        total: 5.962133916683182
        tree:
        - score: 2.3021358869347655
          weight: 5
          category: dataAvailability
          branches:
          - null
          - null
        - score: 2.3021358869347655
          weight: 5
          category: dataAvailability
          branches:
          - null
          - null
      properties:
        total:
          format: double
          type: number
        tree:
          items:
            $ref: '#/components/schemas/transpaerScoreBranch'
          type: array
      required:
      - total
      - tree
      type: object
    transpaerScoreBranch:
      description: Part of explanation of calculation of the Transpaer score.
      example:
        score: 2.3021358869347655
        weight: 5
        category: dataAvailability
        branches:
        - null
        - null
      properties:
        category:
          $ref: '#/components/schemas/transpaerScoreCategory'
        weight:
          type: integer
        score:
          format: double
          type: number
        branches:
          items:
            $ref: '#/components/schemas/transpaerScoreBranch'
          type: array
      required:
      - branches
      - category
      - score
      - weight
      type: object
    transpaerScoreCategory:
      description: Categories in the transpaer score
      enum:
      - dataAvailability
      - producerKnown
      - productionPlaceKnown
      - idKnown
      - categoryAssigned
      - category
      - warrantyLength
      - numCerts
      - atLeastOneCert
      - atLeastTwoCerts
      type: string
    tcoMedallion:
      description: Details of TCO evaluation.
      example:
        brandName: brandName
      properties:
        brandName:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
      required:
      - brandName
      type: object
    productFull:
      description: Full product data.
      example:
        images:
        - image: image
          source: null
        - image: image
          source: null
        names:
        - text: text
          source: transpaer
        - text: text
          source: transpaer
        manufacturers:
        - badges:
          - bcorp
          - bcorp
          scores:
          - score: 0
            scorerName: fti
          - score: 0
            scorerName: fti
          name: name
          description:
            text: text
            source: null
          organisationIds:
            wiki:
            - null
            - null
            vat:
            - null
            - null
            domains:
            - null
            - null
        - badges:
          - bcorp
          - bcorp
          scores:
          - score: 0
            scorerName: fti
          - score: 0
            scorerName: fti
          name: name
          description:
            text: text
            source: null
          organisationIds:
            wiki:
            - null
            - null
            vat:
            - null
            - null
            domains:
            - null
            - null
        productIds:
          gtins:
          - null
          - null
          wiki:
          - null
          - null
          eans:
          - null
          - null
        medallions:
        - euEcolabel:
            matchAccuracy: 0.6027456183070403
          tco:
            brandName: brandName
          transpaer:
            score:
              total: 5.962133916683182
              tree:
              - score: 2.3021358869347655
                weight: 5
                category: dataAvailability
                branches:
                - null
                - null
              - score: 2.3021358869347655
                weight: 5
                category: dataAvailability
                branches:
                - null
                - null
          variant: bCorp
          fti:
            score: 1
          bcorp:
            report_url: report_url
            id: id
        - euEcolabel:
            matchAccuracy: 0.6027456183070403
          tco:
            brandName: brandName
          transpaer:
            score:
              total: 5.962133916683182
              tree:
              - score: 2.3021358869347655
                weight: 5
                category: dataAvailability
                branches:
                - null
                - null
              - score: 2.3021358869347655
                weight: 5
                category: dataAvailability
                branches:
                - null
                - null
          variant: bCorp
          fti:
            score: 1
          bcorp:
            report_url: report_url
            id: id
        origins:
        - null
        - null
        alternatives:
        - category_label: category_label
          category_id: category_id
          alternatives:
          - badges:
            - bcorp
            - bcorp
            productIds:
              gtins:
              - null
              - null
              wiki:
              - null
              - null
              eans:
              - null
              - null
            scores:
            - score: 0
              scorerName: fti
            - score: 0
              scorerName: fti
            name: name
            description:
              text: text
              source: null
          - badges:
            - bcorp
            - bcorp
            productIds:
              gtins:
              - null
              - null
              wiki:
              - null
              - null
              eans:
              - null
              - null
            scores:
            - score: 0
              scorerName: fti
            - score: 0
              scorerName: fti
            name: name
            description:
              text: text
              source: null
        - category_label: category_label
          category_id: category_id
          alternatives:
          - badges:
            - bcorp
            - bcorp
            productIds:
              gtins:
              - null
              - null
              wiki:
              - null
              - null
              eans:
              - null
              - null
            scores:
            - score: 0
              scorerName: fti
            - score: 0
              scorerName: fti
            name: name
            description:
              text: text
              source: null
          - badges:
            - bcorp
            - bcorp
            productIds:
              gtins:
              - null
              - null
              wiki:
              - null
              - null
              eans:
              - null
              - null
            scores:
            - score: 0
              scorerName: fti
            - score: 0
              scorerName: fti
            name: name
            description:
              text: text
              source: null
        media:
        - mentions:
          - link: link
            title: title
          - link: link
            title: title
          icon: icon
        - mentions:
          - link: link
            title: title
          - link: link
            title: title
          icon: icon
        descriptions:
        - text: text
          source: null
        - text: text
          source: null
        shopping:
        - shop: fairphone
          link: link
          description: description
        - shop: fairphone
          link: link
          description: description
      properties:
        productIds:
          $ref: '#/components/schemas/productIds'
        names:
          items:
            $ref: '#/components/schemas/shortText'
          type: array
        descriptions:
          items:
            $ref: '#/components/schemas/longText'
          type: array
        images:
          items:
            $ref: '#/components/schemas/image'
          type: array
        origins:
          items:
            $ref: '#/components/schemas/regionCode'
          type: array
        manufacturers:
          items:
            $ref: '#/components/schemas/organisationShort'
          type: array
        alternatives:
          items:
            $ref: '#/components/schemas/categoryAlternatives'
          type: array
        medallions:
          items:
            $ref: '#/components/schemas/medallion'
          type: array
        shopping:
          items:
            $ref: '#/components/schemas/shoppingEntry'
          type: array
        media:
          items:
            $ref: '#/components/schemas/medium'
          type: array
      required:
      - alternatives
      - descriptions
      - images
      - manufacturers
      - medallions
      - media
      - names
      - productIds
      - shopping
      type: object
    organisationShort:
      description: Extract from organisation data.
      example:
        badges:
        - bcorp
        - bcorp
        scores:
        - score: 0
          scorerName: fti
        - score: 0
          scorerName: fti
        name: name
        description:
          text: text
          source: null
        organisationIds:
          wiki:
          - null
          - null
          vat:
          - null
          - null
          domains:
          - null
          - null
      properties:
        organisationIds:
          $ref: '#/components/schemas/organisationIds'
        name:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
        description:
          $ref: '#/components/schemas/longText'
        badges:
          items:
            $ref: '#/components/schemas/badgeName'
          type: array
        scores:
          items:
            $ref: '#/components/schemas/score'
          type: array
      required:
      - badges
      - name
      - organisationIds
      - scores
      type: object
    categoryAlternatives:
      description: List of product alternative in the given category.
      example:
        category_label: category_label
        category_id: category_id
        alternatives:
        - badges:
          - bcorp
          - bcorp
          productIds:
            gtins:
            - null
            - null
            wiki:
            - null
            - null
            eans:
            - null
            - null
          scores:
          - score: 0
            scorerName: fti
          - score: 0
            scorerName: fti
          name: name
          description:
            text: text
            source: null
        - badges:
          - bcorp
          - bcorp
          productIds:
            gtins:
            - null
            - null
            wiki:
            - null
            - null
            eans:
            - null
            - null
          scores:
          - score: 0
            scorerName: fti
          - score: 0
            scorerName: fti
          name: name
          description:
            text: text
            source: null
      properties:
        category_id:
          type: string
        category_label:
          type: string
        alternatives:
          items:
            $ref: '#/components/schemas/productShort'
          type: array
      required:
      - alternatives
      - category_id
      - category_label
      type: object
    shoppingEntry:
      description: Describes a link to a shop
      example:
        shop: fairphone
        link: link
        description: description
      properties:
        shop:
          $ref: '#/components/schemas/verifiedShop'
        link:
          type: string
        description:
          description: "Short string for labels, titles, summaries..."
          maxLength: 1024
          type: string
      required:
      - description
      - link
      - shop
      type: object
    verifiedShop:
      description: Enumerates verified shops.
      enum:
      - fairphone
      - amazon
      type: string
    category:
      description: ID of a category.
      type: string
    categoryFull:
      description: Full category data.
      example:
        supercategories:
        - id: id
          label: label
        - id: id
          label: label
        label: label
        subcategories:
        - id: id
          label: label
        - id: id
          label: label
        status: exploratory
        products:
        - badges:
          - bcorp
          - bcorp
          productIds:
            gtins:
            - null
            - null
            wiki:
            - null
            - null
            eans:
            - null
            - null
          scores:
          - score: 0
            scorerName: fti
          - score: 0
            scorerName: fti
          name: name
          description:
            text: text
            source: null
        - badges:
          - bcorp
          - bcorp
          productIds:
            gtins:
            - null
            - null
            wiki:
            - null
            - null
            eans:
            - null
            - null
          scores:
          - score: 0
            scorerName: fti
          - score: 0
            scorerName: fti
          name: name
          description:
            text: text
            source: null
      properties:
        label:
          type: string
        status:
          $ref: '#/components/schemas/categoryStatus'
        subcategories:
          items:
            $ref: '#/components/schemas/categoryShort'
          type: array
        supercategories:
          items:
            $ref: '#/components/schemas/categoryShort'
          type: array
        products:
          items:
            $ref: '#/components/schemas/productShort'
          type: array
      required:
      - label
      - products
      - status
      - subcategories
      - supercategories
      type: object
    categoryStatus:
      description: Enumerates organisation ID variants.
      enum:
      - exploratory
      - incomplete
      - satisfactory
      - complete
      - broad
      type: string
    categoryShort:
      description: Short category data.
      example:
        id: id
        label: label
      properties:
        id:
          type: string
        label:
          type: string
      required:
      - id
      - label
      type: object

